apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-2-ingress-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    customer: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /{{ .Release.Namespace }}/{{ .Values.type }}
            pathType: Prefix
            backend:
              service:
                name: service-2-{{ .Release.Namespace }}
                port:
                  name: service-2