apiVersion: v1
kind: Service
metadata:
  name: service-2-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: service-2-{{ .Release.Namespace }}
    customer: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: service-2
      protocol: TCP
  selector:
    app: service-2
    customer: {{ .Release.Namespace }}